/*****************************************************************
 *
 *  This file automatically generated - DO NOT EDIT!
 *
 *****************************************************************/

#ifndef EPILOGUE_INSTALL_H
#define EPILOGUE_INSTALL_H

#define INSTALL_ON_LITTLE_ENDIAN 0
#define INSTALL_ON_BIG_ENDIAN 1
#define INSTALL_OEM_LAYOUT_GLUE_MACROS 0
#define INSTALL_TYPECHECKING_LAYOUT_GLUE_MACROS 0
#define INSTALL_UNALIGNED_BIGENDIAN_LAYOUT_GLUE_MACROS 0
#define INSTALL_COMMON 1
#define INSTALL_COMMON_FIXED64 1
#define INSTALL_COMMON_PRNG 0
#define INSTALL_COMMON_MD4 0
#define INSTALL_COMMON_MD5 1
#define INSTALL_COMMON_SHA 1
#define INSTALL_COMMON_HMAC 1
#define INSTALL_COMMON_DES 1
#define INSTALL_COMMON_3DES 0
#define INSTALL_COMMON_ESP_3DES 0
#define INSTALL_COMMON_DES_TEST 0
#define INSTALL_COMMON_DES_FAKE 0
#define INSTALL_COMMON_STRTOL 0
#define INSTALL_COMMON_STRTOUL 0
#define INSTALL_COMMON_STRICMP 0
#define INSTALL_COMMON_STRNICMP 0
#define INSTALL_COMMON_MEMCMP 0
#define INSTALL_COMMON_SNPRINTF 0
#define INSTALL_COMMON_DYNAMIC_COMP_CONFIG 0
/*#define INSTALL_COMMON_DYNAMIC_COMP_CONFIG 1*/
#define INSTALL_ENVOY 1
#define INSTALL_ENVOY_SNMP_GROUP_V1 1
#define INSTALL_ENVOY_SNMP_GROUP_V2 1
#define INSTALL_ENVOY_SNMP_VERSION_1 1
#define INSTALL_ENVOY_SNMP_VERSION_2 1
/*#define INSTALL_ENVOY_SNMP_VERSION_3 0 *//* change by cpf 0*/
#define INSTALL_ENVOY_SNMP_VERSION_3 1
#define INSTALL_ENVOY_USE_MIBCOMPILER 1
#define INSTALL_ENVOY_MAIN_AGENT 1
#define INSTALL_ENVOY_SNMP_UTIL_MACROS 0
/*#define INSTALL_ENVOY_MD5 0*/
#define INSTALL_ENVOY_MD5 1
/*#define INSTALL_ENVOY_SHA 0*/
#define INSTALL_ENVOY_SHA 1
/*#define INSTALL_ENVOY_DES 0*/
#define INSTALL_ENVOY_DES 1
#define INSTALL_ENVOY_SNMP_RFC1445_VIEWS 0/*change by cpf 1*/
#define INSTALL_ENVOY_SNMP_RFC2275_VIEWS 1 /*change by cpf 0*/
#define INSTALL_ENVOY_TWO_CHAR_MACROS 1
#define INSTALL_ENVOY_SNMP_V3_TARGET 1
/*#define INSTALL_ENVOY_SNMP_V3_TARGET 1*/
#define INSTALL_ENVOY_SNMP_V3_NOTIFY 1
/*#define INSTALL_ENVOY_SNMP_V3_NOTIFY 1*/
#define INSTALL_ENVOY_SNMP_V3_PROXY 0
#define INSTALL_ENVOY_SNMP_COEXISTENCE 0
/*#define INSTALL_ENVOY_SNMP_COEXISTENCE 1*/
#define INSTALL_ENVOY_SNMP_PROXY 0
#define INSTALL_ENVOY_EPI_SUBAGENT_SCHEME 0
#define INSTALL_ENVOY_EPI_MASTER 0
#define INSTALL_ENVOY_EPI_SUB 0
#define INSTALL_ENVOY_EPI_NEXT_SWAP_VERSIONS 0
#define INSTALL_ENVOY_AGENTX 1
#define INSTALL_ENVOY_AGENTX_MASTER 0
#define INSTALL_ENVOY_AGENTX_SUB 0 
#define INSTALL_ENVOY_AGENTX_INDEX 0
#define INSTALL_ENVOY_AGENTX_NEXT_CHECK 1
#define INSTALL_ENVOY_AGENTX_2257_RANGE 0
#define INSTALL_ENVOY_ENTITY_MIB 0
#define INSTALL_ENVOY_SNMP_LOCK 1
#define INSTALL_ENVOY_LOCK_INDEPENDENT 1
#define INSTALL_ENVOY_CONTINUE_REENTRANT 1
#define INSTALL_ENVOY_SNMP_SERIALIZE 0
#define INSTALL_ENVOY_HEAP_LARGE_VARS 0
#define INSTALL_ENVOY_SNMP_USE_V2_TYPES 1
#define INSTALL_ENVOY_PSOS 0
#define INSTALL_ENVOY_PSOS_CONFIG 0
#define INSTALL_ENVOY_VXWORKS_IPV6 0
#define INSTALL_ENVOY_TEST 0
#define INSTALL_ATTACHE 0
#define INSTALL_ATTACHE_MIB 0
#define INSTALL_ENVOY_VXWORKS 1
#define INSTALL_SNARK_LIB 0
#define INSTALL_ENVOY_VXWORKS_SUBAGENT 0
#define INSTALL_ENVOY_VXWORKS_RFC2233 1
#define INSTALL_SNMP_VXWORKS_VIRTUAL_STACK 0
#define INSTALL_ENVOY_VXWORKS_TAE 1

#endif /* EPILOGUE_INSTALL_H */
