set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /Project/Trunk/Src_Linux/tplink/buildroot/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc)
set(CMAKE_CXX_COMPILER /Project/Trunk/Src_Linux/tplink/buildroot/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-g++)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -Os " CACHE STRING "Buildroot CFLAGS" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -Os " CACHE STRING "Buildroot CXXFLAGS" FORCE)
set(CMAKE_INSTALL_SO_NO_EXE 0)
set(CMAKE_PROGRAM_PATH "/Project/Trunk/Src_Linux/tplink/buildroot/host/usr/bin")
set(CMAKE_FIND_ROOT_PATH "/Project/Trunk/Src_Linux/tplink/buildroot/host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "/Project/Trunk/Src_Linux/tplink/buildroot/host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot")
